### ISSUE TITLE
Hot to make pulse to decay faster?

### ISSUE THREAD

**Issue by MarcinOrlowski** [DevLight-Mobile-Agency/PulseView#2]
I wanted to make pulse "short" so it is not spreading across the whole parent container (which is match_parent/match_parent). I ended with PulseView wrapped into another ViewGroup container but it still looks bad as it is just being clipped to parent dimensions and not that the pulse fades out faster. How can I set the pulse to decay faster?

**Comment by GIGAMOLE** [comment]
Hello. Thanks for a question. U can set such parameter as pulse_measure which define the side where pulse finishing. In demo case its height. You need to set the width and set some margins to your view. Also you can spawn pulse period tine shorter.
