### ISSUE TITLE
Does it supports SVG?

### ISSUE THREAD

**Issue by derrysd** [DevLight-Mobile-Agency/PulseView#3]
Sorry, I mean Vector path icon in XML.

**Comment by GIGAMOLE** [comment]
Hello. No. But i can do this for you. Thanks.

**Comment by derrysd** [comment]
Sure, it would be a great enhancement.
Thanks, GIGAMOLE!

**Comment by GIGAMOLE** [comment]
Hello again. You can try vesrion 1.0.1 and set SVG. Thanks for enhancement.
