### ISSUE TITLE
Pulse appears rotated sometimes.

### ISSUE THREAD

**Issue by embydextrous-zz** [DevLight-Mobile-Agency/PulseView#5]
The pulse icon is not rotated but pulse is rotated by 180 degree sometimes.

**Comment by GIGAMOLE** [comment]
Hello. Thanks for feedback. I dont know what are your talking about. What you do for this effect?

**Comment by GIGAMOLE** [comment]
If you rotate your view, you must to call request layout to redraw pulse.

**Comment by embydextrous-zz** [comment]
No I am not rotating my view. But, when I change view's visibility it happens.

**Comment by GIGAMOLE** [comment]
Update 1.0.2 is on the rails. Thanks.
