### ISSUE TITLE
Error: android.content.res.Resources$NotFoundException when set Vector xml drawable.

### ISSUE THREAD

**Issue by asxced** [DevLight-Mobile-Agency/PulseView#7]
also   Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #1: invalid drawable tag vector

**Comment by embydextrous-zz** [comment]
Inside pulseview.java in invalidateIcon() method, instead of using:
`final Drawable iconDrawable = ContextCompat.getDrawable(getContext(), mIconResId);`

use

`final Drawable iconDrawable = AppCompatDrawableManager.get().getDrawable(getContext(), mIconResId);`
